
"""

Find explicit AI-disclosure signals in Firefox commit messages.

Two kinds, reported separately:
  agent-authored  an agent signed the commit. Same agents as AIDev(Li et al. 2025), plus Gemini CLI.
  self-admitted   a human mentions an AI tool (Xiao et al. 2026).  Low precision, should be manually labelled and scored
"""
import csv, json, re


WINDOWS = {
    "human": ("commits_filtered.jsonl", "bugzilla_matched.jsonl"),
    "ai": ("commits_filtered_AI.jsonl", "bugzilla_matched_AI.jsonl"),
}



 # Regex is a mix of the two studies mentioned above, and whatever came out of discover signatures.py
AGENTS = {
    "claude-code": r"noreply@anthropic\.com|co-authored-by:[^\n]*claude"
                   r"|generated (with|using) \[?claude"
                   r"|claude[^\n]{0,20}on the cli"
                   r"|claude-session:",
    "codex":       r"codex@openai\.com|co-authored-by:[^\n]*codex(bot)?\b"
                   r"|chatgpt\.com/codex|generated (with|using) codex",
    "copilot":     r"copilot@users\.noreply\.github\.com|copilot-swe-agent"
                   r"|co-authored-by:[^\n]*\bcopilot\b",
    "cursor":      r"cursoragent|cursor ?composer"
                   r"|co-authored-by:[^\n]*\bcursor\b",
    "devin":       r"devin-ai-integration|devin\.ai"
                   r"|co-authored-by:[^\n]*\bdevin\b",
}

for name, pattern in AGENTS.items():
    AGENTS[name] = re.compile(pattern, re.I)



# from xiaos study, also just general chatbot names n assistance. Needs manual review
SELF_ADMITTED = re.compile(
    r"chat[ \-_]?gpt|co[ \-_]?pilot"
    r"|claude|codex|cursor|gemini|devin|windsurf|aider"
    r"|anthropic|openai|\bllm\b|\bai\b"
    r"|ai[- ](assisted|generated|written)"
    r"|(generated|written|created|authored) (with|by|using)",
    re.I)


# code generation tools that are not AI. This part was suggested by Claude. should help speed up manual labeling
NOISE_CONTEXT = re.compile(
    r"clang-tidy|clang-format|ffmpeg|bindgen|cbindgen|protoc|mach |perfdocs"
    r"|autoconf|automake|cmake|swig|bison|flex|yacc|rustfmt|prettier|eslint"
    r"|generated by the script|wasm2c|wasm-opt|webidl|idl compiler", re.I)
# other features that might be useful for labeling, but not necessarily AI. Also suggested by Claude
FEAUTERS = re.compile(r"machine learning|chatbot|genai|smart ?window", re.I)
TOOLS = re.compile(r"ai for development", re.I)



def load_bugs(path):
    bugs = {}
    for line in open(path):
        b = json.loads(line)
        comp = b["product"] + " :: " + b["component"]
        bugs[str(b["id"])] = (comp, b["whiteboard"]) # ids are looked up as strings
    return bugs


def prelabel(kind, comp, whiteboard, ctx):
    # hopefully speeds up review process
    if kind == "agent-authored":
        return "AGENT_AUTHORED"
    if "[genai]" in whiteboard.lower() or FEAUTERS.search(comp):
        return "FP_FEATURE?"
    if NOISE_CONTEXT.search(ctx):      
        return "FP_NOISE?"
    if TOOLS.search(comp):
        return "FP_TOOLING?"
    return ""

def matched_lines(msg, rx):
    # pulls out the first two lines that match the regex for context when reviewing
    matches = []
    for line in msg.splitlines():
        if rx.search(line):
            matches.append(line.strip()[:120])

    return " || ".join(matches[:2])


for window, (path, bugs_path) in WINDOWS.items():
    
    bugs = load_bugs(bugs_path)

    commits = []
    rows = []
    agents = {}
    
    with open(path) as f:
        for line in f:
            commits.append(json.loads(line))

    for c in commits:
        msg = c["message"]
        identity = f"{c['author_email']} {c['committer_email']}"
        hits = []
        for name, rx in AGENTS.items():
            if rx.search(msg) or rx.search(identity):
                hits.append(name)

        if hits:
            kind, rx = "agent-authored", AGENTS[hits[0]]
            key = "+".join(hits)
            agents[key] = agents.get(key, 0) + 1
        elif SELF_ADMITTED.search(msg):
            kind, rx = "self-admitted", SELF_ADMITTED
        else:
            continue



        bug = re.search(r"bug ?(\d+)", c["subject"], re.I)

        if bug:
            comp, whiteboard = bugs.get(bug.group(1), ("", ""))
        else:
            comp, whiteboard = "", ""

        terms = set()
        for m in rx.finditer(msg):
            terms.add(m.group(0).lower())
        terms = sorted(terms)
        ctx = matched_lines(msg, rx)

        rows.append({
            "hash": c["hash"][:12],
            "date": c["commit_date"][:10],
            "author": c["author_email"],
            "kind": kind,
            "agent": "+".join(hits),
            "component": comp,
            "whiteboard": whiteboard[:60],
            "matched": "|".join(terms)[:80],
            "context": ctx,
            "subject": c["subject"][:100],
            "label": prelabel(kind, comp, whiteboard, ctx),
            "rater": "",
        })

    out = f"ai_candidates_{window}.csv"

    if rows:
        fieldnames = list(rows[0])
    else:
        fieldnames = ["hash"]

    with open(out, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader()
            w.writerows(rows)

    n_agent = sum(agents.values())
    tags = {}
    for r in rows:
        if r["label"].endswith("?"):
            tags[r["label"]] = tags.get(r["label"], 0) + 1

    n_self = len(rows) - n_agent

    print(window + ": " + str(len(commits)) + " commits")
    print("  agent-authored " + str(n_agent) + "   " + str(dict(agents)))
    print("  self-admitted  " + str(n_self) + "   pre-tagged " + str(dict(tags)) + " -> " + out)

    self_rows = []
    for r in rows:
        if r["kind"] == "self-admitted":
            self_rows.append(r)

    terms = {}
    for r in self_rows:
        for t in r["matched"].split("|"):
            if t:
                terms[t] = terms.get(t, 0) + 1

    top_terms = sorted(terms.items(), key=lambda pair: pair[1], reverse=True)[:8]
    for term, n in top_terms:
        print("      " + str(n) + "  " + term)

    comps = {}
    for r in self_rows:
        if r["component"]:
            comps[r["component"]] = comps.get(r["component"], 0) + 1

    if comps:
        print("    components:")
        top_comps = sorted(comps.items(), key=lambda pair: pair[1], reverse=True)[:8]
        for comp, n in top_comps:
            print("      " + str(n) + "  " + comp)